### ISSUE TITLE
Game crash after login

### ISSUE THREAD

**Issue by wolfrik17** [Qouve/IncQol#5]
Game crashes everytime after login, happens with both the latest version and the old one

**Comment by wolfrik17** [comment]
[IncQol.log](https://github.com/Qouve/IncQol/files/2299772/IncQol.log)

**Comment by wolfrik17** [comment]
I removed all other addons and deleted the addons folder and only left the dll file from IncQol to check and it still crashes

**Comment by Qouve** [comment]
Can you delete the addons/incqol folder and see if it still crashs? And do you get a crash window?

**Comment by wolfrik17** [comment]
Still crashes, this is a picture of the crash window
![a](https://user-images.githubusercontent.com/23453638/44345964-72f0bb00-a49d-11e8-976a-74f88dfdd2a9.png)

**Comment by Qouve** [comment]
Okay, I searched the Module and Exception and found that the crash probably is not due to a failure in my addon.

On one site there is: 
The 0xe06d7363 Kernelbase.dll error may occur if the Windows system files are damaged. The corrupted system files entries can be a real threat to your computer. [Link](https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_call-insiderplat_pc/mail-crashes-with-the-following-error-0xe06d7363/c27ca06b-2af7-4c53-9859-ab9b891561cf)

The same site and another one I found said that creating a new user account will probably fix it.

**Comment by wolfrik17** [comment]
Never thought about googling the error since I just assumed it was a problem with the addon since everything else works fine. Did a bit more research and it looks like it might indeed be an issue caused by windows gonna try a few possible solutions and report back if I fix it

**Comment by wolfrik17** [comment]
Making a new user account for windows allowed me to start the game without it crashing while running the addon. Now I got to find a way to fix my own account since I'm not going to switch accounts every time I want to play GW2

**Comment by wolfrik17** [comment]
I decided to make a new user account on windows and backup all my data but something weird is going on. If the game is in windowed fullscreen mode it will crash with the same error. If it's in fullscreen mode it doesn't crash but it doesn't render the game. I can see the cursor and hear the music but can't do anything else, it just shows me my desktop. Last time I tried it on a new account I just assumed it was fixed because it didn't crash and I didn't wait enough for the game to start but that was not the case.

**Comment by Qouve** [comment]
I can not help you with this error, as I can not recreate it. Maybe there is a compatibility problem, you are missing c++ redistributable or there is still some corrupted files on your pc.

**Comment by CaptainTeddyBear** [comment]
i have the exact same problem As Wolfrik stated at the end ...  with the exact same error he posted long ago, i'm really frustrated, creating a new user did not solve the problem! please any suggestions i might try that could make it work ?

**Comment by Qouve** [comment]
Do you have any errors in the windows event log?

**Comment by wolfrik17** [comment]
Ok, I found out what was causing the issue. If the Guild Wars 2 executable is not named 'Gw2-64.exe' the game will crash after login. Maybe you can figure out what causes this issue (I know arcDPS also had some problems with the name of the exe file) and add a note on the main page so others know about it.

**Comment by Qouve** [comment]
Weird bug, I will add it.
